In [3]:
import pandas as pd

df = pd.read_csv("/Users/isirirram/DAV/house price/For_EDA_dataset.csv")
print(df.shape)
df.head()

(153430, 15)

,Unnamed: 0,property_type,price,location,city,province_name,latitude,longitude,baths,purpose,bedrooms,date_added,agency,agent,Area_in_Marla
0,0,Flat,10000000,G-10,Islamabad,Islamabad Capital,33.679890,73.012640,2,For Sale,2,2019-02-04,Self,Self,4.0
1,1,Flat,6900000,E-11,Islamabad,Islamabad Capital,33.700993,72.971492,3,For Sale,3,2019-05-04,Self,Self,5.6
2,2,House,16500000,G-15,Islamabad,Islamabad Capital,33.631486,72.926559,6,For Sale,5,2019-07-17,Self,Self,8.0
3,3,House,43500000,Bani Gala,Islamabad,Islamabad Capital,33.707573,73.151199,4,For Sale,4,2019-04-05,Self,Self,40.0
4,4,House,7000000,DHA Defence,Islamabad,Islamabad Capital,33.492591,73.301339,3,For Sale,3,2019-07-10,Easy Property,Muhammad Junaid Ceo Muhammad Shahid Director,8.0

In [4]:
df_mean = df.copy()
num_cols = df_mean.select_dtypes(include='number').columns

for col in num_cols:
    mean_val = df[col].mean()
    print("Mean", col, ":", mean_val)
    df_mean[col] = df_mean[col].fillna(mean_val)

print(df_mean.isnull().sum())
df_mean.head()

Mean Unnamed: 0 : 82557.39826631037
Mean price : 18418205.378335398
Mean latitude : 29.880766834072062
Mean longitude : 71.26212730986654
Mean baths : 2.955738773381998
Mean bedrooms : 3.2594081991787784
Mean Area_in_Marla : 12.333483021573358
Unnamed: 0       0
property_type    0
price            0
location         0
city             0
province_name    0
latitude         0
longitude        0
baths            0
purpose          0
bedrooms         0
date_added       0
agency           0
agent            0
Area_in_Marla    0
dtype: int64

,Unnamed: 0,property_type,price,location,city,province_name,latitude,longitude,baths,purpose,bedrooms,date_added,agency,agent,Area_in_Marla
0,0,Flat,10000000,G-10,Islamabad,Islamabad Capital,33.679890,73.012640,2,For Sale,2,2019-02-04,Self,Self,4.0
1,1,Flat,6900000,E-11,Islamabad,Islamabad Capital,33.700993,72.971492,3,For Sale,3,2019-05-04,Self,Self,5.6
2,2,House,16500000,G-15,Islamabad,Islamabad Capital,33.631486,72.926559,6,For Sale,5,2019-07-17,Self,Self,8.0
3,3,House,43500000,Bani Gala,Islamabad,Islamabad Capital,33.707573,73.151199,4,For Sale,4,2019-04-05,Self,Self,40.0
4,4,House,7000000,DHA Defence,Islamabad,Islamabad Capital,33.492591,73.301339,3,For Sale,3,2019-07-10,Easy Property,Muhammad Junaid Ceo Muhammad Shahid Director,8.0

In [5]:
df_median = df.copy()

for col in num_cols:
    df_median[col] = df_median[col].fillna(df[col].median())

print(df_median.isnull().sum())
df_median.head()

Unnamed: 0       0
property_type    0
price            0
location         0
city             0
province_name    0
latitude         0
longitude        0
baths            0
purpose          0
bedrooms         0
date_added       0
agency           0
agent            0
Area_in_Marla    0
dtype: int64

,Unnamed: 0,property_type,price,location,city,province_name,latitude,longitude,baths,purpose,bedrooms,date_added,agency,agent,Area_in_Marla
0,0,Flat,10000000,G-10,Islamabad,Islamabad Capital,33.679890,73.012640,2,For Sale,2,2019-02-04,Self,Self,4.0
1,1,Flat,6900000,E-11,Islamabad,Islamabad Capital,33.700993,72.971492,3,For Sale,3,2019-05-04,Self,Self,5.6
2,2,House,16500000,G-15,Islamabad,Islamabad Capital,33.631486,72.926559,6,For Sale,5,2019-07-17,Self,Self,8.0
3,3,House,43500000,Bani Gala,Islamabad,Islamabad Capital,33.707573,73.151199,4,For Sale,4,2019-04-05,Self,Self,40.0
4,4,House,7000000,DHA Defence,Islamabad,Islamabad Capital,33.492591,73.301339,3,For Sale,3,2019-07-10,Easy Property,Muhammad Junaid Ceo Muhammad Shahid Director,8.0

In [6]:
df_ffill = df.copy()
cat_cols = df_ffill.select_dtypes(exclude='number').columns

print("Before Forward Fill:")
print(df_ffill[cat_cols].isnull().sum())

df_ffill[cat_cols] = df_ffill[cat_cols].ffill()

print("\nAfter Forward Fill:")
print(df_ffill[cat_cols].isnull().sum())

Before Forward Fill:
property_type    0
location         0
city             0
province_name    0
purpose          0
date_added       0
agency           0
agent            0
dtype: int64

After Forward Fill:
property_type    0
location         0
city             0
province_name    0
purpose          0
date_added       0
agency           0
agent            0
dtype: int64

In [7]:
from sklearn.preprocessing import LabelEncoder

df_label = df_ffill.copy()

for col in cat_cols:
    encoder = LabelEncoder()
    df_label[col + '_Encoded'] = encoder.fit_transform(df_label[col])
    print(col, encoder.classes_)

df_label.head()

property_type ['Farm House' 'Flat' 'House' 'Lower Portion' 'Penthouse' 'Room'
 'Upper Portion']
location ['12th Avenue' '204 Chak Road' '7th Avenue' ... 'Zubair Colony'
 'Zulfiqar Colony' 'circular road']
city ['Faisalabad' 'Islamabad' 'Karachi' 'Lahore' 'Rawalpindi']
province_name ['Islamabad Capital' 'Punjab' 'Sindh']
purpose ['For Rent' 'For Sale']
date_added ['2018-08-05' '2018-08-06' '2018-08-07' '2018-08-08' '2018-08-09'
 '2018-08-20' '2018-08-21' '2018-08-22' '2018-09-04' '2018-09-05'
 '2018-09-06' '2018-09-07' '2018-09-08' '2018-09-19' '2018-09-20'
 '2018-09-21' '2018-10-04' '2018-10-05' '2018-10-06' '2018-10-07'
 '2018-10-08' '2018-10-19' '2018-10-20' '2018-10-21' '2018-11-03'
 '2018-11-05' '2018-11-06' '2018-11-07' '2018-11-10' '2018-11-18'
 '2018-11-19' '2018-11-20' '2018-12-03' '2018-12-05' '2018-12-06'
 '2018-12-07' '2018-12-10' '2018-12-18' '2018-12-19' '2018-12-20'
 '2019-01-03' '2019-01-04' '2019-01-05' '2019-01-06' '2019-01-09'
 '2019-01-17' '2019-01-18' '2019-01-19' '2019-02-01' '2019-02-02'
 '2019-02-03' '2019-02-04' '2019-02-05' '2019-02-16' '2019-02-17'
 '2019-02-18' '2019-03-03' '2019-03-04' '2019-03-05' '2019-03-06'
 '2019-03-07' '2019-03-10' '2019-03-18' '2019-03-19' '2019-03-20'
 '2019-04-02' '2019-04-03' '2019-04-04' '2019-04-05' '2019-04-06'
 '2019-04-09' '2019-04-17' '2019-04-18' '2019-04-19' '2019-05-02'
 '2019-05-03' '2019-05-04' '2019-05-05' '2019-05-06' '2019-05-09'
 '2019-05-17' '2019-05-18' '2019-05-19' '2019-06-01' '2019-06-02'
 '2019-06-03' '2019-06-04' '2019-06-05' '2019-06-06' '2019-06-07'
 '2019-06-10' '2019-06-11' '2019-06-12' '2019-06-13' '2019-06-14'
 '2019-06-16' '2019-06-17' '2019-06-18' '2019-06-19' '2019-06-20'
 '2019-06-21' '2019-06-24' '2019-06-25' '2019-06-26' '2019-06-27'
 '2019-06-28' '2019-06-29' '2019-06-30' '2019-07-01' '2019-07-02'
 '2019-07-03' '2019-07-04' '2019-07-05' '2019-07-08' '2019-07-09'
 '2019-07-10' '2019-07-11' '2019-07-12' '2019-07-13' '2019-07-14'
 '2019-07-15' '2019-07-16' '2019-07-17' '2019-07-18']
agency ['1 One Enterprises' '10 Star Enterprises' '101 Real Estate & Builders'
 ... 'i Real Estate (Insaf Group)'
 'iftikhar Chaudhary Real Estate Consultant' 'maliktasaduq110@gmail. com']
agent ['-AK Builders' '4 Season Real Estate' '5G Properties' ...
 'zohaib rehman muhamm' 'zohib tipu' 'zubair  Iqbal']

,Unnamed: 0,property_type,price,location,city,province_name,latitude,longitude,baths,purpose,...,agent,Area_in_Marla,property_type_Encoded,location_Encoded,city_Encoded,province_name_Encoded,purpose_Encoded,date_added_Encoded,agency_Encoded,agent_Encoded
0,0,Flat,10000000,G-10,Islamabad,Islamabad Capital,33.679890,73.012640,2,For Sale,...,Self,4.0,1,488,1,0,1,51,4878,8454
1,1,Flat,6900000,E-11,Islamabad,Islamabad Capital,33.700993,72.971492,3,For Sale,...,Self,5.6,1,415,1,0,1,76,4878,8454
2,2,House,16500000,G-15,Islamabad,Islamabad Capital,33.631486,72.926559,6,For Sale,...,Self,8.0,2,493,1,0,1,122,4878,8454
3,3,House,43500000,Bani Gala,Islamabad,Islamabad Capital,33.707573,73.151199,4,For Sale,...,Self,40.0,2,211,1,0,1,68,4878,8454
4,4,House,7000000,DHA Defence,Islamabad,Islamabad Capital,33.492591,73.301339,3,For Sale,...,Muhammad Junaid Ceo Muhammad Shahid Director,8.0,2,351,1,0,1,115,1892,6262

In [8]:
%pip install scikit-learn

Requirement already satisfied: scikit-learn in /Users/isirirram/jupyter-env/lib/python3.14/site-packages (1.9.1)
Requirement already satisfied: numpy>=1.24.1 in /Users/isirirram/jupyter-env/lib/python3.14/site-packages (from scikit-learn) (2.5.3)
Requirement already satisfied: scipy>=1.10.0 in /Users/isirirram/jupyter-env/lib/python3.14/site-packages (from scikit-learn) (1.18.1)
Requirement already satisfied: joblib>=1.4.0 in /Users/isirirram/jupyter-env/lib/python3.14/site-packages (from scikit-learn) (1.6.0)
Requirement already satisfied: narwhals>=2.0.1 in /Users/isirirram/jupyter-env/lib/python3.14/site-packages (from scikit-learn) (2.26.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in /Users/isirirram/jupyter-env/lib/python3.14/site-packages (from scikit-learn) (3.7.0)
Requirement already satisfied: cloudpickle>=3.0 in /Users/isirirram/jupyter-env/lib/python3.14/site-packages (from joblib>=1.4.0->scikit-learn) (3.1.2)
Note: you may need to restart the kernel to use updated packages.

In [9]:
encoded_df = pd.get_dummies(df_ffill, columns=list(cat_cols), dtype=int)
encoded_df.head()

,Unnamed: 0,price,latitude,longitude,baths,bedrooms,Area_in_Marla,property_type_Farm House,property_type_Flat,property_type_House,...,agent_xpert real estate,agent_yasir jhangir,agent_yasir raza,agent_yawar khan,agent_zafar khan,agent_zafar zia,agent_zahid ch,agent_zohaib rehman muhamm,agent_zohib tipu,agent_zubair Iqbal
0,0,10000000,33.679890,73.012640,2,2,4.0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1,1,6900000,33.700993,72.971492,3,3,5.6,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2,2,16500000,33.631486,72.926559,6,5,8.0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,3,43500000,33.707573,73.151199,4,4,40.0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,4,7000000,33.492591,73.301339,3,3,8.0,0,0,1,...,0,0,0,0,0,0,0,0,0,0